### PR TITLE
Checks if we need to downscale the height after upscaling the width

### PR DESCRIPTION
**Pull request by bkositza**
Depending on how the maximum permitted sizes for an image are specified, it may be that both the width and height are too small and therefore need to be scaled up. If we scale up the width first, it may well be that the height is too high for the specified maximum height.

Example:
Maximum width: 100px
Maximum height: 20px

Image:
50px wide and 15px high

After we have scaled up the width, the image would be :
100px wide and 30px high

The height of the image is now too high and we need to scale it down once.

### CODE REVIEW

**Review by sabieber — APPROVED** [review]

**Review by ymo-sci — APPROVED** [review]

**Review by fhaScireum — COMMENTED** [review]
Don't we also need to upscale the height? Wouldn't we need to upscale the width if needed, upscale the height if needed, and then down scale both to fit?

**Comment by bkositza** [comment]
> Don't we also need to upscale the height? Wouldn't we need to upscale the width if needed, upscale the height if needed, and then down scale both to fit?

Do you have an example of when we need to scale up the height and width? In my opinion, it is sufficient if we scale one of them up and then scale the other down.

**Comment by sabieber** [comment]
Langsam wären ein paar Testcases für die Logik glaub garnicht so verkehrt

**Comment by fhaScireum** [comment]
> > Don't we also need to upscale the height? Wouldn't we need to upscale the width if needed, upscale the height if needed, and then down scale both to fit?
> 
> Do you have an example of when we need to scale up the height and width? In my opinion, it is sufficient if we scale one of them up and then scale the other down.

Now that I think about it a bit more, the behaviour now should be correct.

**Review by fhaScireum — APPROVED** [review]

**Comment by bkositza** [comment]
> Langsam wären ein paar Testcases für die Logik glaub garnicht so verkehrt

Done ;)

**Review by mko-sci — APPROVED** [review]

**Review by mko-sci — APPROVED** [review]

**Pull request merged**
