### PR TITLE
Lokalise: Translations update

### PR DESCRIPTION
**Pull request by scireumskip**
This pull request was initiated by Lokalise (user Marcus Korinth) at 2024-04-10 11:53:02

### CODE REVIEW

**Review by mko-sci — APPROVED** [review]

**Review by jakobvogel — APPROVED** [review]

**Review by mkeckmkeck — APPROVED** [review]

**Review by sabieber — APPROVED** [review]

**Review by idlira — APPROVED** [review]
New terms are translated as Continue / Return instead of Next / Previous.
Can we kinda specify a meaning in Lokalise? If not, let it stay as is.
Eg. 
Portuguese: Continuar / De volta -> Próximo / Anterior
Spanish: Continuar / Regressar -> Siguiente / Anterior
probably French and Italian is also wrong.
What do you think @jakobvogel

**Review by fhaScireum — APPROVED** [review]

**Comment by jakobvogel** [comment]
> New terms are translated as Continue / Return instead of Next / Back. Can we kinda specify a meaning in Lokalise? If not, let it stay as is. Eg. Portuguese: Continuar / De volta -> Próximo / Anterior Spanish: Continuar / Regressar -> Siguiente / Anterior probably French and Italian is also wrong. What do you think @jakobvogel

I agree, @idlira. Portuguese and Spanish you know better than any of us, of course 😇 … For French, see for instance https://french.stackexchange.com/questions/12969/translation-of-it-terms-like-close-next-search-etc **Précédent** / **Suivant** … for Italian, I found a use on the website of _ISTITUTO GEOGRAFICO MILITARE_ which belongs to the Italian army and therefore should know about the wording:

Screenshot 2024-04-10 at 12 10 05

**Comment by idlira** [comment]
> > New terms are translated as Continue / Return instead of Next / Back. Can we kinda specify a meaning in Lokalise? If not, let it stay as is. Eg. Portuguese: Continuar / De volta -> Próximo / Anterior Spanish: Continuar / Regressar -> Siguiente / Anterior probably French and Italian is also wrong. What do you think @jakobvogel
> 
> I agree, @idlira. Portuguese and Spanish you know better than any of us, of course 😇 … For French, see for instance https://french.stackexchange.com/questions/12969/translation-of-it-terms-like-close-next-search-etc **Précédent** / **Suivant** … for Italian, I found a use on the website of _ISTITUTO GEOGRAFICO MILITARE_ which belongs to the Italian army and therefore should know about the wording:
> 
> Screenshot 2024-04-10 at 12 10 05

@mko-sci are we using DE or EN as base language for translations? I thought we startet using EN since it yields better results. When I look at the german text, kinda answer why we are getting Continue x Next:

```
Pagination.next = Weiter
Pagination.previous = Zurück
```

**Comment by mko-sci** [comment]
> > > New terms are translated as Continue / Return instead of Next / Back. Can we kinda specify a meaning in Lokalise? If not, let it stay as is. Eg. Portuguese: Continuar / De volta -> Próximo / Anterior Spanish: Continuar / Regressar -> Siguiente / Anterior probably French and Italian is also wrong. What do you think @jakobvogel
> > 
> > 
> > I agree, @idlira. Portuguese and Spanish you know better than any of us, of course 😇 … For French, see for instance https://french.stackexchange.com/questions/12969/translation-of-it-terms-like-close-next-search-etc **Précédent** / **Suivant** … for Italian, I found a use on the website of _ISTITUTO GEOGRAFICO MILITARE_ which belongs to the Italian army and therefore should know about the wording:
> > Screenshot 2024-04-10 at 12 10 05
> 
> @mko-sci are we using DE or EN as base language for translations? I thought we startet using EN since it yields better results. When I look at the german text, kinda answer why we are getting Continue x Next:
> 
> ```
> Pagination.next = Weiter
> Pagination.previous = Zurück
> ```

We are using english as base language. The problem is when there are to little keys to translate no order can be placed as the total costs are below 0,00€. Therefore I have to manually translate every key with the onboard helpers (and or AI). These onboard helpers always use the base language of the project which is German. I cant change it here. Only within the order can I specify the source language to translate from

**Comment by mko-sci** [comment]
Suggestion: 
get me a list of what it should be in which language and I change it manually after merging this pr...but I will change it in Lokalise of course and then we will have a separate PR for the fix

**Pull request merged**
